import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../(frontend)/globals.css";
import { Toaster } from "@/components/ui/sonner"

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-blackfade2 ${montserrat.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
